[project]
name = "tinyjaxley"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "diffrax>=0.6.2",
    "equinox>=0.11.11",
    "jax[cpu]>=0.4.38",
    "jaxley>=0.5.0",
    "matplotlib>=3.10.0",
    "networkx>=3.4.2",
    "numpy>=2.2.1",
    "pandas>=2.2.3",
    "ruff>=0.14.8",
    "sbi>=0.22.0",
]

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
    "pytest>=8.3.4",
]
